### ISSUE TITLE
English Version

### ISSUE THREAD

**Issue by patronum08** [yangzhch6/InterMWP#1]
Hi,
    Thanks for your valueable work in InterMWP and LogicSlover! Do you also provide English version of InterMWP?
Best,

**Comment by yangzhch6** [comment]
The source of our data is in Chinese, and in order to better preserve the original semantics, we did not use translation tools to translate it into English. We also didn't use human translators because that would increase the cost of data annotation.

If you're desperate for English data, I think using GPT-4 / ChatGPT  is a cheaper and more cost-effective way.
